name: Echo API

on:
  push:
    paths:
      - 'src/echo-api/**'
      - 'src/echo-api.tests/**'
      - '.github/workflows/echo-api.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet restore src/echo-api/echo-api.csproj
        dotnet restore src/echo-api.tests/echo-api.tests.csproj
    
    - name: Build
      run: |
        dotnet build --no-restore src/echo-api/echo-api.csproj
        dotnet build --no-restore src/echo-api.tests/echo-api.tests.csproj
    
    - name: Test
      run: dotnet test --no-build src/echo-api.tests/echo-api.tests.csproj --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Todo API Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

  publish:
    if: github.ref == 'refs/heads/main'
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: ${{ secrets.DOCKER_USER }}/aptiv-echo-api:${{ github.run_id }}

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - run: |
          docker build -f Dockerfile.multi -t ${{ env.IMAGE_NAME}} src/echo-api
          docker push ${{ env.IMAGE_NAME}}


